"""
Rule-based executive brief generator.

Produces a structured markdown report from API data and the computed risk
score. No LLM or external service is involved — logic is fully transparent
and auditable.
"""

from datetime import date


def generate_executive_brief(
    risk_result: dict,
    weather_geneva: dict,
    weather_doha: dict,
    flight_data: dict,
    event_data: dict,
    event_params: dict,
) -> str:
    """
    Assemble a professional executive brief in markdown format.

    All text is generated by deterministic rules so that every sentence
    can be traced back to an input value.
    """
    score = risk_result["score"]
    category = risk_result["category"]

    start: date = event_params["start_date"]
    end: date = event_params["end_date"]
    guests: int = event_params["guests"]
    budget_chf: float = event_params["budget_chf"]

    doha_temp = weather_doha.get("temp_max", 30.0)
    doha_precip = weather_doha.get("precip_prob", 5.0) or 0.0
    geneva_precip = weather_geneva.get("precip_prob", 50.0) or 0.0
    doha_source = weather_doha.get("source", "seasonal_average")
    geneva_source = weather_geneva.get("source", "seasonal_average")

    supplier = float(event_data.get("supplier_readiness", 85))
    vip = float(event_data.get("vip_arrivals_completed", 70))
    guest_conf = float(event_data.get("guest_confirmation", 80))
    security = float(event_data.get("security_clearance", 91))

    direct = flight_data.get("direct_flight_available", True)
    travel_h = flight_data.get("avg_travel_duration_hours", 6.5)
    disruption = flight_data.get("disruption_risk_label", "Low")
    buffer_h = flight_data.get("recommended_buffer_hours", 3)

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append("## Executive Event Intelligence Brief")
    lines.append(
        f"**Route:** Geneva → Doha &nbsp;|&nbsp; "
        f"**Period:** {start.strftime('%d %b %Y')} – {end.strftime('%d %b %Y')} &nbsp;|&nbsp; "
        f"**Guests:** {guests} &nbsp;|&nbsp; "
        f"**Budget:** CHF {budget_chf:,.0f}"
    )
    lines.append(
        f"**Overall Risk:** {category} &nbsp;({score}/100) &nbsp;|&nbsp; "
        f"*Generated by rule-based engine — no AI/LLM involved*"
    )
    lines.append("---")

    # ── Weather ───────────────────────────────────────────────────────────────
    lines.append("### 🌡️ Weather Outlook")
    weather_note = "live forecast data" if doha_source == "live_forecast" else "seasonal climate averages"
    lines.append(f"*Source: {weather_note}*")
    lines.append("")

    if doha_temp > 40:
        doha_comment = (
            f"**Doha — Extreme heat conditions** ({doha_temp:.0f}°C max). "
            "All outdoor activities must be eliminated from the programme. "
            "Indoor climate control confirmation is mandatory at least 72 h before the event."
        )
    elif doha_temp > 35:
        doha_comment = (
            f"**Doha — Elevated temperatures** ({doha_temp:.0f}°C max). "
            "Outdoor programme elements should be minimised or moved to early morning. "
            "Confirm venue air conditioning capacity."
        )
    elif doha_temp > 28:
        doha_comment = (
            f"**Doha — Warm conditions** ({doha_temp:.0f}°C max). "
            "Standard climate protocols apply. Outdoor elements are manageable in shaded settings."
        )
    else:
        doha_comment = (
            f"**Doha — Favourable climate** ({doha_temp:.0f}°C max). "
            "Weather presents minimal risk; outdoor programme elements are viable."
        )

    lines.append(doha_comment)

    geneva_weather_note = "live forecast data" if geneva_source == "live_forecast" else "seasonal climate averages"
    if geneva_precip > 65:
        lines.append(
            f"**Geneva — Elevated precipitation probability** ({geneva_precip:.0f}%, {geneva_weather_note}). "
            "Verify covered transfer arrangements between hotel and airport."
        )
    elif geneva_precip > 45:
        lines.append(
            f"**Geneva — Moderate precipitation probability** ({geneva_precip:.0f}%, {geneva_weather_note}). "
            "Standard wet-weather contingency applies."
        )
    else:
        lines.append(
            f"**Geneva** — Departure conditions are favourable ({geneva_precip:.0f}% precipitation probability)."
        )

    lines.append("---")

    # ── Logistics ─────────────────────────────────────────────────────────────
    lines.append("### 🏛️ Logistics Status")
    lines.append("*Source: Mock event management API (demo)*")
    lines.append("")

    def _status(val: float, thresholds=(90, 80)) -> str:
        if val >= thresholds[0]:
            return "✅ On track"
        if val >= thresholds[1]:
            return "⚠️ Monitor"
        return "🔴 Action required"

    lines.append(f"- **Supplier Readiness:** {supplier:.0f}% — {_status(supplier)}")
    lines.append(f"- **VIP Arrival Confirmations:** {vip:.0f}% — {_status(vip)}")
    lines.append(f"- **Guest Confirmation Rate:** {guest_conf:.0f}% — {_status(guest_conf)}")
    lines.append(f"- **Security Clearance:** {security:.0f}% — {_status(security)}")
    lines.append("---")

    # ── Travel ────────────────────────────────────────────────────────────────
    lines.append("### ✈️ Travel Intelligence")
    lines.append("*Source: Mock flight intelligence API (demo)*")
    lines.append("")

    flight_comment = (
        "Direct Geneva–Doha service (Qatar Airways QR) is confirmed."
        if direct
        else "No direct service available. Connection routing via Frankfurt adds ~3 h to total travel time."
    )
    lines.append(
        f"{flight_comment} "
        f"Average travel duration: **{travel_h:.1f} h**. "
        f"Travel disruption risk: **{disruption}**. "
        f"Recommended guest arrival buffer: **+{buffer_h} h**."
    )
    lines.append("---")

    # ── Recommendations ───────────────────────────────────────────────────────
    lines.append("### 📋 Key Recommendations")
    recommendations: list[str] = []

    if doha_temp > 38:
        recommendations.append(
            "Confirm indoor climate control for all Doha venues at least 72 h before the event."
        )
    if vip < 80:
        recommendations.append(
            f"Activate personal VIP liaison protocol — {42 - int(event_data.get('vip_guests', {}).get('confirmed', 30))} "
            "confirmations are still pending."
        )
    if supplier < 85:
        recommendations.append(
            "Schedule an emergency supplier briefing within 48 h to resolve outstanding readiness gaps."
        )
    if disruption in ("Moderate", "High"):
        recommendations.append(
            f"Increase travel buffer to +{buffer_h + 2} h for all VIP guests and monitor real-time disruption feeds."
        )
    if not direct:
        recommendations.append(
            "Brief all guests on connection protocol and ensure dedicated airline liaison at the transit hub."
        )
    if geneva_precip > 60:
        recommendations.append(
            "Activate wet-weather contingency for Geneva departure-day transfers."
        )
    if security < 85:
        recommendations.append(
            "Escalate security clearance process — current rate is below the 85% threshold."
        )

    if not recommendations:
        recommendations.append(
            "Maintain current readiness levels and conduct a final comprehensive review 48 h before the event."
        )

    for i, rec in enumerate(recommendations, 1):
        lines.append(f"{i}. {rec}")

    lines.append("---")
    lines.append(
        "*This brief is auto-generated by a deterministic rule-based engine from live and mock API data. "
        "No generative AI is involved. All logic is auditable in `src/analytics/report_generator.py`.*"
    )

    return "\n\n".join(lines)
